"""Self-improvement module - Agent learns from experience."""
import json
import time
from pathlib import Path
from typing import Optional


class DreamConsolidator:
    """Consolidates experience into memory and skills.

    Dream-like process that reviews past work and creates
    improvements for future tasks.
    """

    def __init__(self, storage_dir: Path = None):
        self.storage_dir = storage_dir or Path.cwd() / ".mini-agent-cli"
        self.memory_dir = self.storage_dir / ".memory"
        self.skills_dir = self.storage_dir / "skills"
        self.memory_dir.mkdir(parents=True, exist_ok=True)
        self.skills_dir.mkdir(parents=True, exist_ok=True)

    def analyze_success_patterns(self, completed_tasks: list[dict]) -> list[str]:
        """Analyze patterns from successful tasks."""
        patterns = []

        # Simple pattern analysis
        for task in completed_tasks:
            if task.get("success"):
                task_type = task.get("type", "unknown")
                patterns.append(f"Successfully completed {task_type} tasks")

        return patterns

    def should_create_skill(self, task_history: list[dict]) -> tuple[bool, Optional[str]]:
        """Check if a recurring pattern should be turned into a skill."""
        task_types = {}

        for task in task_history:
            task_type = task.get("type", "unknown")
            task_types[task_type] = task_types.get(task_type, 0) + 1

        # Create skill if task appears 3+ times
        for task_type, count in task_types.items():
            if count >= 3:
                return True, task_type

        return False, None

    def consolidate(self, task_history: list[dict], memory_type: str = "feedback") -> str:
        """Consolidate experience into memory.

        Creates a memory entry summarizing lessons learned.
        """
        patterns = self.analyze_success_patterns(task_history)
        should_create, skill_type = self.should_create_skill(task_history)

        summary = f"## 经验总结\n\n"
        summary += f"完成 {len(task_history)} 个任务\n\n"

        if patterns:
            summary += "### 成功模式\n"
            for p in patterns[:5]:
                summary += f"- {p}\n"

        if should_create and skill_type:
            summary += f"\n建议创建技能: {skill_type}\n"

        # Save to memory
        memory_file = self.memory_dir / f"dream_{int(time.time())}.md"
        memory_file.write_text(summary)

        return summary

    def suggest_improvements(self, failed_tasks: list[dict]) -> list[str]:
        """Suggest improvements based on failures."""
        suggestions = []

        for task in failed_tasks:
            error = task.get("error", "")
            if error:
                suggestions.append(f"改进建议: {error[:100]}")

        return suggestions[:5]


class SelfImprovingAgent:
    """Agent with self-improvement capabilities."""

    def __init__(self):
        self.dream = DreamConsolidator()
        self.task_count = 0
        self.success_threshold = 3

    def record_task(self, task: dict) -> None:
        """Record a completed task for analysis."""
        self.task_count += 1

        # Check if it's time to consolidate
        if self.task_count % 10 == 0:
            self.run_dream_cycle()

    def should_update_memory(self, task: dict) -> bool:
        """Check if task should update memory."""
        if task.get("success"):
            return self.task_count % 5 == 0
        return True  # Always remember failures

    def create_skill_from_pattern(self, pattern: str, context: str) -> str:
        """Create a skill from a recurring pattern."""
        skill_file = self.skills_dir / f"{pattern}.md"
        content = f"""# Skill: {pattern}

## Pattern
{context}

## Created
Auto-generated by self-improving agent
"""
        skill_file.write_text(content)
        return f"Created skill: {pattern}"

    def run_dream_cycle(self) -> str:
        """Run a dream consolidation cycle."""
        # This would be called during idle time
        return "Dream cycle completed"


__all__ = ["DreamConsolidator", "SelfImprovingAgent"]
